from io import BytesIO
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak
)
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import letter
from reportlab.platypus.flowables import HRFlowable
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.styles import ParagraphStyle


def build_pdf(data):

    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40,
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        'TitleStyle',
        parent=styles['Heading1'],
        fontSize=28,
        leading=34,
        textColor=colors.HexColor('#2563eb'),
        alignment=TA_CENTER,
        spaceAfter=30,
    )

    section_style = ParagraphStyle(
        'SectionStyle',
        parent=styles['Heading2'],
        fontSize=18,
        leading=22,
        textColor=colors.HexColor('#0f172a'),
        spaceBefore=20,
        spaceAfter=12,
    )

    body_style = ParagraphStyle(
        'BodyStyle',
        parent=styles['BodyText'],
        fontSize=11,
        leading=18,
        textColor=colors.HexColor('#334155'),
    )

    story = []

    # =====================================================
    # HEADER
    # =====================================================

    story.append(
        Paragraph(
            "Synaptrix AI",
            title_style
        )
    )

    story.append(
        Paragraph(
            "Adaptive Research Intelligence Report",
            styles['Heading3']
        )
    )

    story.append(Spacer(1, 20))

    topic = data.get("topic", "Unknown Topic")

    story.append(
        Paragraph(
            f"<b>Research Topic:</b> {topic}",
            body_style
        )
    )

    story.append(Spacer(1, 16))

    story.append(
        HRFlowable(
            width="100%",
            color=colors.HexColor('#cbd5e1')
        )
    )

    # =====================================================
    # AI AGENT OUTPUTS
    # =====================================================

    sections = [
        ("Research Summary", data.get("summary")),
        ("Research Analysis", data.get("analysis")),
        ("Research Gaps", data.get("gaps")),
        ("Cross-Paper Synthesis", data.get("synthesis")),
    ]

    for title, content in sections:

        story.append(
            Paragraph(title, section_style)
        )

        cleaned = (content or "Not available")
        cleaned = cleaned.replace("\n", "<br/>")

        story.append(
            Paragraph(cleaned, body_style)
        )

        story.append(Spacer(1, 20))

    # =====================================================
    # PAPERS
    # =====================================================

    papers = data.get("top_papers", [])

    story.append(PageBreak())

    story.append(
        Paragraph(
            "Top Research Papers",
            section_style
        )
    )

    for idx, paper in enumerate(papers, start=1):

        title = paper.get("title", "Untitled")
        abstract = paper.get("abstract", "No abstract")
        authors = ", ".join(paper.get("authors", []))
        year = paper.get("year", "Unknown")

        story.append(
            Paragraph(
                f"<b>{idx}. {title}</b>",
                body_style
            )
        )

        story.append(
            Paragraph(
                f"<b>Authors:</b> {authors}",
                body_style
            )
        )

        story.append(
            Paragraph(
                f"<b>Year:</b> {year}",
                body_style
            )
        )

        story.append(
            Paragraph(
                abstract,
                body_style
            )
        )

        story.append(Spacer(1, 20))

    # =====================================================
    # FOOTER
    # =====================================================

    story.append(Spacer(1, 30))

    story.append(
        HRFlowable(
            width="100%",
            color=colors.HexColor('#cbd5e1')
        )
    )

    story.append(Spacer(1, 12))

    story.append(
        Paragraph(
            "Generated by Synaptrix AI — Multi-Agent Research Intelligence System",
            body_style
        )
    )

    doc.build(story)

    pdf = buffer.getvalue()

    buffer.close()

    return pdf